package com.dogdog.nomat.domain.room.model;

public enum RoomDomainEventType {
    MEMBER_JOINED,
    MEMBER_LEFT,
    HOST_CHANGED,
    MEMBER_KICKED,
    ROOM_SETTINGS_UPDATED,
    ROOM_CLOSED,
    GAME_STARTED,
    QUESTION_STARTED,
    HINT_REVEALED,
    CHAT_MESSAGE,
    CORRECT_ANSWER,
    SCORE_UPDATED,
    SKIP_VOTE_UPDATED,
    QUESTION_AUDIO_LOAD_FAILED,
    QUESTION_ENDED,
    GAME_ENDED
}
